"""Add ingestion failure tracking.

Revision ID: fe486f01aa9b
Revises: 006_referees_rotations
Create Date: 2026-03-29 20:04:00.011692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe486f01aa9b'
down_revision: Union[str, None] = '006_referees_rotations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_failures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('payload_summary', sa.Text(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_failures_job_name'), 'ingestion_failures', ['job_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_failures_job_name'), table_name='ingestion_failures')
    op.drop_table('ingestion_failures')
    # ### end Alembic commands ###
