<#
.SYNOPSIS
    Prepare `.env` for container-first development.

.DESCRIPTION
    After cloning the repo, run this script once to:
      1. Generate `.env` from repo defaults
      2. Optionally hydrate secrets from Azure Container Apps if az CLI is logged in

    The Python toolchain is owned by the dev container. This script does
    not create a virtual environment or install Python packages.

.EXAMPLE
    .\scripts\setup-env.ps1
    .\scripts\setup-env.ps1 -Force   # overwrite existing .env
#>
param(
  [switch]$Force
)

$ErrorActionPreference = "Stop"

$ROOT = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$ENV_FILE = Join-Path $ROOT ".env"

$RG = "nba_gbsv_v6_az"
$APP = "ca-nba-gbsv-v6-worker"

if ((Test-Path $ENV_FILE) -and -not $Force) {
  Write-Host ".env already exists at $ENV_FILE" -ForegroundColor Yellow
  Write-Host "Use -Force to overwrite." -ForegroundColor Yellow
  exit 0
}

$databaseUrl = "postgresql+asyncpg://postgres:postgres@localhost:5432/nba_gbsv"
$oddsKey = "dev-odds-placeholder"
$bballKey = "dev-basketball-placeholder"
$teamsWebhook = ""
$logLevel = "INFO"

Write-Host "Preparing .env (optionally from ACA: $APP in $RG)..." -ForegroundColor Cyan

# Check if logged in before trying to pull secrets
try {
  $azActive = az account show --query "environment" -o tsv 2>$null
  if (-not $azActive) {
      throw "Not logged into az CLI"
  }
  
  # Fetch secrets
  $oddsKey = az containerapp secret show -n $APP -g $RG --secret-name odds-api-key --query "value" -o tsv
  $bballKey = az containerapp secret show -n $APP -g $RG --secret-name basketball-api-key --query "value" -o tsv
  $teamsWebhook = az containerapp secret show -n $APP -g $RG --secret-name teams-webhook-url --query "value" -o tsv 2>$null
  
  if (-not $oddsKey -or -not $bballKey) {
    throw "Failed to retrieve one or more secrets from ACA."
  }
} catch {
    Write-Host "Warning: Could not fetch secrets from ACA ($($_.Exception.Message))." -ForegroundColor Yellow
    Write-Host "Writing local defaults from the repo template instead." -ForegroundColor Yellow
}

# Build .env content
$content = @"
# ── Auto-generated by scripts/setup-env.ps1 ──────────
# Source of truth: pyproject.toml + dev container
# Optional secret source: ACA secrets from $APP in $RG
# Re-run: .\scripts\setup-env.ps1 -Force

# ── Required secrets ──────────────────────────────────
ODDS_API_KEY=$oddsKey
BASKETBALL_API_KEY=$bballKey

# ── Database ──────────────────────────────────────────
DATABASE_URL=$databaseUrl

# ── App ───────────────────────────────────────────────
APP_ENV=development
LOG_LEVEL=$logLevel

# ── Azure (production only) ───────────────────────────
AZURE_KEY_VAULT_URL=

# ── Teams delivery ────────────────────────────────────
TEAMS_WEBHOOK_URL=$teamsWebhook
"@

Set-Content -Path $ENV_FILE -Value $content -Encoding UTF8
Write-Host "Created $ENV_FILE" -ForegroundColor Green
Write-Host "Done. Open the repo in the dev container and run: python -m src migrate" -ForegroundColor Green
