<#
.SYNOPSIS
    Pull secrets from Azure Container Apps and create a local .env file.

.DESCRIPTION
    After cloning the repo, run this script once to generate .env with
    the correct API keys and DATABASE_URL from the ACA deployment.

    Requires: az CLI logged in with access to the nba_gbsv_v6_az resource group.

.EXAMPLE
    .\scripts\setup-env.ps1
    .\scripts\setup-env.ps1 -Force   # overwrite existing .env
#>
param(
  [switch]$Force
)

$ErrorActionPreference = "Stop"

$RG = "nba_gbsv_v6_az"
$APP = "ca-nba-gbsv-v6-worker"
$ENV_FILE = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\.env"))

if ((Test-Path $ENV_FILE) -and -not $Force) {
  Write-Host ".env already exists at $ENV_FILE" -ForegroundColor Yellow
  Write-Host "Use -Force to overwrite." -ForegroundColor Yellow
  exit 0
}

Write-Host "Pulling secrets from ACA ($APP in $RG)..." -ForegroundColor Cyan

# Fetch secrets
$dbUrl = az containerapp secret show -n $APP -g $RG --secret-name database-url --query "value" -o tsv
$oddsKey = az containerapp secret show -n $APP -g $RG --secret-name odds-api-key --query "value" -o tsv
$bballKey = az containerapp secret show -n $APP -g $RG --secret-name basketball-api-key --query "value" -o tsv
$teamsWebhook = az containerapp secret show -n $APP -g $RG --secret-name teams-webhook-url --query "value" -o tsv 2>$null

if (-not $dbUrl -or -not $oddsKey -or -not $bballKey) {
  Write-Error "Failed to retrieve one or more secrets from ACA. Are you logged in? (az login)"
  exit 1
}

# Build .env content
$content = @"
# ── Auto-generated by scripts/setup-env.ps1 ──────────
# Source: ACA secrets from $APP in $RG
# Re-run: .\scripts\setup-env.ps1 -Force

# ── Required secrets ──────────────────────────────────
ODDS_API_KEY=$oddsKey
BASKETBALL_API_KEY=$bballKey

# ── Database ──────────────────────────────────────────
DATABASE_URL=$dbUrl

# ── App ───────────────────────────────────────────────
APP_ENV=development
LOG_LEVEL=INFO

# ── Teams delivery ────────────────────────────────────
TEAMS_WEBHOOK_URL=$teamsWebhook
"@

Set-Content -Path $ENV_FILE -Value $content -Encoding UTF8
Write-Host "Created $ENV_FILE" -ForegroundColor Green
Write-Host "Done. You can now run: python -m src migrate" -ForegroundColor Green
