<#
.SYNOPSIS
    Bootstrap local development: create venv, install dependencies,
    and pull secrets from Azure Container Apps.

.DESCRIPTION
    After cloning the repo, run this script once to:
      1. Create a .venv (if missing) and install requirements-dev.txt
      2. Generate .env with the correct API keys / DATABASE_URL from the ACA deployment

    Requires: Python 3.12+, az CLI logged in with access to the nba_gbsv_v6_az resource group.

.EXAMPLE
    .\scripts\setup-env.ps1
    .\scripts\setup-env.ps1 -Force   # overwrite existing .env
#>
param(
  [switch]$Force
)

$ErrorActionPreference = "Stop"

$ROOT = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$VENV = Join-Path $ROOT ".venv"
$ENV_FILE = Join-Path $ROOT ".env"

# ── 1. Create venv + install deps ────────────────────────────────
if (-not (Test-Path (Join-Path $VENV "Scripts\python.exe"))) {
  Write-Host "Creating virtual environment..." -ForegroundColor Cyan
  python -m venv $VENV
  if ($LASTEXITCODE -ne 0) { Write-Error "Failed to create venv"; exit 1 }
}

$pip = Join-Path $VENV "Scripts\pip.exe"
$python = Join-Path $VENV "Scripts\python.exe"
Write-Host "Upgrading pip..." -ForegroundColor Cyan
& $python -m pip install --quiet --upgrade pip

Write-Host "Installing dependencies..." -ForegroundColor Cyan

# Workaround for Python 3.14 + binary dependencies
# Try binary install first for sensitive packages to avoid build failures on 3.14
& $pip install --quiet --only-binary :all: scikit-learn xgboost pandas numpy asyncpg psycopg2-binary

# Filter out packages already installed as binaries from requirements pass
$reqPath = Join-Path $ROOT "requirements-dev.txt"
$runtimeReqPath = Join-Path $ROOT "requirements.txt"
$tempReq = Join-Path $ROOT "temp-requirements.txt"

# Helper to filter a file
function Filter-Requirements($path) {
    if (Test-Path $path) {
        return Get-Content $path | Where-Object { 
            $_ -notmatch "^scikit-learn" -and 
            $_ -notmatch "^xgboost" -and 
            $_ -notmatch "^pandas" -and 
            $_ -notmatch "^numpy" -and
            $_ -notmatch "^asyncpg" -and
            $_ -notmatch "^psycopg2-binary" -and
            $_ -notmatch "^-r" -and
            $_ -notmatch "^\s*$" 
        }
    }
    return @()
}

Write-Host "Installing remaining dependencies..." -ForegroundColor Cyan
$combinedReqs = @()
$combinedReqs += Filter-Requirements $runtimeReqPath
$combinedReqs += Filter-Requirements $reqPath
$combinedReqs | Set-Content $tempReq

& $pip install --quiet -r $tempReq
Remove-Item $tempReq

Write-Host "Dependencies installed." -ForegroundColor Green

# ── 2. Pull secrets from ACA ─────────────────────────────────────

$RG = "nba_gbsv_v6_az"
$APP = "ca-nba-gbsv-v6-worker"

if ((Test-Path $ENV_FILE) -and -not $Force) {
  Write-Host ".env already exists at $ENV_FILE" -ForegroundColor Yellow
  Write-Host "Use -Force to overwrite." -ForegroundColor Yellow
  exit 0
}

Write-Host "Pulling secrets from ACA ($APP in $RG)..." -ForegroundColor Cyan

# Check if logged in before trying to pull secrets
try {
  $azActive = az account show --query "environment" -o tsv 2>$null
  if (-not $azActive) {
      throw "Not logged into az CLI"
  }
  
  # Fetch secrets
  $dbUrl = az containerapp secret show -n $APP -g $RG --secret-name database-url --query "value" -o tsv
  $oddsKey = az containerapp secret show -n $APP -g $RG --secret-name odds-api-key --query "value" -o tsv
  $bballKey = az containerapp secret show -n $APP -g $RG --secret-name basketball-api-key --query "value" -o tsv
  $teamsWebhook = az containerapp secret show -n $APP -g $RG --secret-name teams-webhook-url --query "value" -o tsv 2>$null
  
  if (-not $dbUrl -or -not $oddsKey -or -not $bballKey) {
    throw "Failed to retrieve one or more secrets from ACA."
  }
} catch {
    Write-Host "Warning: Could not fetch secrets from ACA ($($_.Exception.Message))." -ForegroundColor Yellow
    Write-Host "Proceeding with dummy/placeholder values for local development." -ForegroundColor Yellow
    
    $dbUrl = "postgresql://postgres:postgres@localhost:5432/nba_gbsv_v6"
    $oddsKey = "YOUR_ODDS_API_KEY"
    $bballKey = "YOUR_BASKETBALL_API_KEY"
    $teamsWebhook = "YOUR_TEAMS_WEBHOOK_URL"
}

# Build .env content
$content = @"
# ── Auto-generated by scripts/setup-env.ps1 ──────────
# Source: ACA secrets from $APP in $RG
# Re-run: .\scripts\setup-env.ps1 -Force

# ── Required secrets ──────────────────────────────────
ODDS_API_KEY=$oddsKey
BASKETBALL_API_KEY=$bballKey

# ── Database ──────────────────────────────────────────
DATABASE_URL=$dbUrl

# ── App ───────────────────────────────────────────────
APP_ENV=development
LOG_LEVEL=INFO

# ── Teams delivery ────────────────────────────────────
TEAMS_WEBHOOK_URL=$teamsWebhook
"@

Set-Content -Path $ENV_FILE -Value $content -Encoding UTF8
Write-Host "Created $ENV_FILE" -ForegroundColor Green
Write-Host "Done. You can now run: python -m src migrate" -ForegroundColor Green
